### PR TITLE
Fix parse quoted values as strings

### LINKED ISSUE #116: Parse quoted values as strings
Is it possible to configure Yams to parse a quoted value (single or double quotes) as a string, instead of trying to convert to an assumed Swift type?
```yams
version: "10.10" // want it to parse to "10.10" String instead of 10.1 Float
```
I know it's possible to use an explicit type tag as a workaround, but it would be nice to be able to just quote a value which I thought is the standard way of specifying strings in yaml.
```
version: !!str '10.10' // correctly parses as "10.10"
```
This would fix https://github.com/yonaskolb/XcodeGen/issues/268

### PR DESCRIPTION
**Pull request by norio-nomura**
Fix #116

### CODE REVIEW

File: Sources/Yams/Parser.swift [hunk 1]
```diff
@@ -287,9 +287,8 @@ private class Event {
         return Node.Scalar.Style(rawValue: event.data.scalar.style.rawValue)!
     }
     var scalarTag: String? {
```
Comment (keith) [inline Sources/Yams/Parser.swift]: This can return a `String` now

Comment (jpsim) [reply Sources/Yams/Parser.swift]: It can't since `string(from:)` still returns `String?`
